In [1]:
import numpy as np
import pandas as pd
from itertools import combinations

In [2]:
# Function to generate matrices and compute XORs and determinant
def generate_matrices(matrix_size):
    num_elements = matrix_size ** 2
    num_ones = num_elements // 2
    comb_indices = list(combinations(range(num_elements), num_ones))
    data = []

    for indices in comb_indices:
        matrix = np.zeros(num_elements, dtype=int)
        matrix[list(indices)] = 1
        matrix = matrix.reshape(matrix_size, matrix_size)

        row_xor = np.bitwise_xor.reduce(matrix, axis=1)
        col_xor = np.bitwise_xor.reduce(matrix, axis=0)
        determinant = np.linalg.det(matrix)

        data.append({'Matrix': matrix, 'Row XOR': row_xor, 'Column XOR': col_xor, 'Determinant': determinant})

    return pd.DataFrame(data)

In [3]:
# Generate matrices and the relevant data
df = generate_matrices(4)

In [4]:
# Filter for determinants
df_zero_det = df[df['Determinant'] == 0]
df_nonzero_det = df[df['Determinant'] != 0]

In [5]:
#filter for XOR data
xor_one = lambda x: np.all(x == 1)
df_xor_ones_nonzero_det = df[
    df.apply(lambda row: xor_one(row['Row XOR']) and xor_one(row['Column XOR']), axis=1) & (df['Determinant'] != 0)]
df_xor_ones_zero_det = df[
    df.apply(lambda row: xor_one(row['Row XOR']) and xor_one(row['Column XOR']), axis=1) & (df['Determinant'] == 0)]

In [6]:
#Defining a function that prints the df and the summary for it
def print_df_summary(df, name):
    print(f"Summary of {name}:")
    print(df[['Row XOR', 'Column XOR', 'Determinant']])
    print("\n" + "-" * 50 + "\n")

In [7]:
# Print summaries for all DataFrames
print_df_summary(df, "Main DataFrame")
print_df_summary(df_zero_det, "DataFrame with Zero Determinant")
print_df_summary(df_nonzero_det, "DataFrame with Non-Zero Determinant")
print_df_summary(df_xor_ones_nonzero_det, "DataFrame with XORs All 1s and Non-Zero Determinant")
print_df_summary(df_xor_ones_zero_det, "DataFrame with XORs All 1s and Zero Determinant")

Summary of Main DataFrame:
            Row XOR    Column XOR  Determinant
0      [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
1      [0, 1, 1, 0]  [1, 0, 0, 1]          0.0
2      [0, 1, 1, 0]  [0, 1, 0, 1]          0.0
3      [0, 1, 1, 0]  [0, 0, 1, 1]          0.0
4      [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
...             ...           ...          ...
12865  [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
12866  [0, 1, 1, 0]  [0, 0, 1, 1]          0.0
12867  [0, 1, 1, 0]  [0, 1, 0, 1]          0.0
12868  [0, 1, 1, 0]  [1, 0, 0, 1]          0.0
12869  [0, 0, 0, 0]  [0, 0, 0, 0]          0.0

[12870 rows x 3 columns]

--------------------------------------------------

Summary of DataFrame with Zero Determinant:
            Row XOR    Column XOR  Determinant
0      [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
1      [0, 1, 1, 0]  [1, 0, 0, 1]          0.0
2      [0, 1, 1, 0]  [0, 1, 0, 1]          0.0
3      [0, 1, 1, 0]  [0, 0, 1, 1]          0.0
4      [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
... 

In [8]:
#Further Analysis for relationship between XORs and determinants
df_identical_xor_nonzero_det = df[df.apply(lambda row: np.array_equal(row['Row XOR'], row['Column XOR']) and row['Determinant'] != 0, axis=1)]
print_df_summary(df_identical_xor_nonzero_det, "DataFrame with Identical XORs and Non-Zero Determinant")


Summary of DataFrame with Identical XORs and Non-Zero Determinant:
            Row XOR    Column XOR  Determinant
64     [0, 0, 1, 1]  [0, 0, 1, 1]         -1.0
68     [0, 0, 1, 1]  [0, 0, 1, 1]          1.0
93     [0, 0, 1, 1]  [0, 0, 1, 1]          1.0
100    [0, 0, 1, 1]  [0, 0, 1, 1]         -1.0
132    [0, 1, 0, 1]  [0, 1, 0, 1]          1.0
...             ...           ...          ...
12274  [1, 0, 0, 1]  [1, 0, 0, 1]         -1.0
12297  [1, 0, 0, 1]  [1, 0, 0, 1]          1.0
12300  [1, 0, 0, 1]  [1, 0, 0, 1]          1.0
12329  [1, 1, 1, 1]  [1, 1, 1, 1]         -1.0
12334  [1, 1, 1, 1]  [1, 1, 1, 1]          1.0

[720 rows x 3 columns]

--------------------------------------------------



In [9]:
df_all_zeros_det_zero = df[df.apply(lambda row: np.all(row['Row XOR'] == 0) and np.all(row['Column XOR'] == 0) and row['Determinant'] == 0, axis=1)]

In [10]:
# Non-Zero Determinant and All XORs 0
df_all_zeros_nonzero_det = df[df.apply(lambda row: np.all(row['Row XOR'] == 0) and np.all(row['Column XOR'] == 0) and row['Determinant'] != 0, axis=1)]

#

In [11]:
# Print summaries for all DataFrames
print_df_summary(df_all_zeros_det_zero, "DataFrame with All Zero XORs and Determinant Zero")
print_df_summary(df_all_zeros_nonzero_det, "DataFrame with Non-Zero Determinant and All XORs 0")


Summary of DataFrame with All Zero XORs and Determinant Zero:
            Row XOR    Column XOR  Determinant
0      [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
30     [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
44     [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
61     [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
79     [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
...             ...           ...          ...
12790  [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
12808  [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
12825  [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
12839  [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
12869  [0, 0, 0, 0]  [0, 0, 0, 0]          0.0

[246 rows x 3 columns]

--------------------------------------------------

Summary of DataFrame with Non-Zero Determinant and All XORs 0:
Empty DataFrame
Columns: [Row XOR, Column XOR, Determinant]
Index: []

--------------------------------------------------



In [12]:
# Either Row XORs or Column XORs is All Zeros
df_either_xor_zeros = df[df.apply(lambda row: np.all(row['Row XOR'] == 0) or np.all(row['Column XOR'] == 0), axis=1)]


In [13]:

# Print summary for the new DataFrame
print_df_summary(df_either_xor_zeros, "DataFrame with Either Row XORs or Column XORs All Zeros")

# Either Row XORs or Column XORs is All Zeros with Non-Zero Determinant
df_either_xor_zeros_nonzero_det = df[df.apply(lambda row: (np.all(row['Row XOR'] == 0) or np.all(row['Column XOR'] == 0)) and row['Determinant'] != 0, axis=1)]


Summary of DataFrame with Either Row XORs or Column XORs All Zeros:
            Row XOR    Column XOR  Determinant
0      [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
4      [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
8      [0, 1, 0, 1]  [0, 0, 0, 0]          0.0
11     [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
15     [0, 1, 0, 1]  [0, 0, 0, 0]          0.0
...             ...           ...          ...
12854  [0, 1, 0, 1]  [0, 0, 0, 0]          0.0
12858  [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
12861  [0, 1, 0, 1]  [0, 0, 0, 0]          0.0
12865  [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
12869  [0, 0, 0, 0]  [0, 0, 0, 0]          0.0

[3222 rows x 3 columns]

--------------------------------------------------



In [14]:
# Print summary for the new DataFrame
print_df_summary(df_either_xor_zeros_nonzero_det, "DataFrame with Either Row XORs or Column XORs All Zeros and Non-Zero Determinant")


Summary of DataFrame with Either Row XORs or Column XORs All Zeros and Non-Zero Determinant:
            Row XOR    Column XOR  Determinant
727    [1, 0, 0, 1]  [0, 0, 0, 0]          2.0
734    [1, 0, 1, 0]  [0, 0, 0, 0]          2.0
736    [1, 0, 0, 1]  [0, 0, 0, 0]         -2.0
743    [1, 0, 1, 0]  [0, 0, 0, 0]         -2.0
805    [1, 1, 0, 0]  [0, 0, 0, 0]          2.0
...             ...           ...          ...
12064  [1, 1, 0, 0]  [0, 0, 0, 0]         -2.0
12126  [1, 0, 1, 0]  [0, 0, 0, 0]          2.0
12133  [1, 0, 0, 1]  [0, 0, 0, 0]          2.0
12135  [1, 0, 1, 0]  [0, 0, 0, 0]         -2.0
12142  [1, 0, 0, 1]  [0, 0, 0, 0]         -2.0

[576 rows x 3 columns]

--------------------------------------------------



In [15]:
def print_matrices(df):
    for index, row in df.iterrows():
        print(f"Matrix #{index + 1}:")
        # Assuming 'Matrix' column exists and contains the matrix in string format
        # If the matrices are stored as numpy arrays or lists, you'll need to convert them to a printable format
        print(row['Matrix'])
        print("\n" + "-"*20 + "\n")


In [16]:
# Call the function to print matrices
print_matrices(df_all_zeros_det_zero)

Matrix #1:
[[1 1 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [0 0 0 0]]

--------------------

Matrix #31:
[[1 1 1 1]
 [1 1 0 0]
 [0 0 1 1]
 [0 0 0 0]]

--------------------

Matrix #45:
[[1 1 1 1]
 [1 1 0 0]
 [0 0 0 0]
 [0 0 1 1]]

--------------------

Matrix #62:
[[1 1 1 1]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 0 0]]

--------------------

Matrix #80:
[[1 1 1 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 1 0 1]]

--------------------

Matrix #89:
[[1 1 1 1]
 [1 0 0 1]
 [0 1 1 0]
 [0 0 0 0]]

--------------------

Matrix #107:
[[1 1 1 1]
 [1 0 0 1]
 [0 0 0 0]
 [0 1 1 0]]

--------------------

Matrix #176:
[[1 1 1 1]
 [0 1 1 0]
 [1 0 0 1]
 [0 0 0 0]]

--------------------

Matrix #198:
[[1 1 1 1]
 [0 1 1 0]
 [0 0 0 0]
 [1 0 0 1]]

--------------------

Matrix #203:
[[1 1 1 1]
 [0 1 0 1]
 [1 0 1 0]
 [0 0 0 0]]

--------------------

Matrix #225:
[[1 1 1 1]
 [0 1 0 1]
 [0 0 0 0]
 [1 0 1 0]]

--------------------

Matrix #286:
[[1 1 1 1]
 [0 0 1 1]
 [1 1 0 0]
 [0 0 0 0]]

--------------------

Matrix #308:
[[1 1 1 1]
 [0 0 1 1]


In [17]:
# Filter for matrices with Zero Determinant and at least one XOR (row or column) being all zeros
df_zero_det_at_least_one_xor_zero = df[df.apply(lambda row: row['Determinant'] == 0 and (np.all(row['Row XOR'] == 0) or np.all(row['Column XOR'] == 0)), axis=1)]


In [18]:
# Print summary for the new DataFrame
print_df_summary(df_zero_det_at_least_one_xor_zero, "DataFrame with Zero Determinant and At Least One XOR Zero")

Summary of DataFrame with Zero Determinant and At Least One XOR Zero:
            Row XOR    Column XOR  Determinant
0      [0, 0, 0, 0]  [0, 0, 0, 0]          0.0
4      [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
8      [0, 1, 0, 1]  [0, 0, 0, 0]          0.0
11     [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
15     [0, 1, 0, 1]  [0, 0, 0, 0]          0.0
...             ...           ...          ...
12854  [0, 1, 0, 1]  [0, 0, 0, 0]          0.0
12858  [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
12861  [0, 1, 0, 1]  [0, 0, 0, 0]          0.0
12865  [0, 1, 1, 0]  [0, 0, 0, 0]          0.0
12869  [0, 0, 0, 0]  [0, 0, 0, 0]          0.0

[2646 rows x 3 columns]

--------------------------------------------------



In [19]:
# Accessing a specific row by index for analysis
pd.set_option("display.max_colwidth", None)
row_index = 727  # Example row index
row_data = df.iloc[row_index]
print(row_data)

Matrix         [[1, 1, 1, 0], [1, 0, 0, 1], [0, 1, 0, 1], [0, 0, 1, 0]]
Row XOR                                                    [1, 0, 0, 1]
Column XOR                                                 [0, 0, 0, 0]
Determinant                                                         2.0
Name: 727, dtype: object
